### ISSUE TITLE
ContainerView Height Crash.

### ISSUE THREAD

**Issue by HackShitUp** [Ramotion/folding-cell#79]
A lot of others mentioned this previously before but I'm also getting the same error. Why is this happening? The answer to this question should be clearly specified in the doc. Everything needs to be significantly clearer.

**Comment by ryandailey100** [comment]
Agreed. I spent over 8 hours trying to implement this into my project and still no success.

**Comment by HackShitUp** [comment]
@ryandailey100 do you know how what the difference between IBInspectable itemCount and kRowsCount is?

**Comment by raypendergraph** [comment]
@HackShitUp, the kRowsCount (I believe) this is because  simply because the model is fake. I think something like this fixes it (but I am still having issues as well): 

```
        do {
            people = try managedContext.fetch(request)
            cellHeights.removeAll()
            
            for _ in 0...people.count {
                cellHeights.append(closedCellHeight)
            }
            
            (self.view as! UITableView).reloadData()
        }
        catch {
            print("Error fetching 'Person': \(error)")
        }
```
... but I'm not sure I get why floats are used here as they are basically used like a flag for the animation state... maybe a [Bool] would be better? Also, the default `itemCount` is 2 which is what I want but that causes a problem in FoldingCell.swift:

```
let itemHeight = (contSize.height - 2 * forgSize.height) / CGFloat(itemCount - 2)
```
... as `itemHeight` will be NaN unless I am missing something. Currently I am getting nil from `UIGraphicsGetCurrentContext()` in `pb_takeSnapshot(_ frame: CGRect) -> UIImage?`. I will update this if I get further.

**Comment by raypendergraph** [comment]
I wanted to leave a separate comment from the discussion above as it's not technically part of the OP's bug description. I think the ContainerView height issue (for my issue at least) stems from the following lines:

```
    // added other views
    let itemHeight = (contSize.height - 2 * forgSize.height) / CGFloat(itemCount - 2)
    
    if itemCount == 2 {
      // decrease containerView height or increase itemCount
      assert(contSize.height - 2 * forgSize.height == 0, "contanerView.height too high")
    }
    // decrease containerView height or increase itemCount
    assert(contSize.height - 2 * forgSize.height >= itemHeight, "contanerView.height too high")
```

as noted above the default `itemCount` is 2 which causes an issue. The workaround seems to be just tell it three and extend the containerView a little beyond the views so those asserts quit complaining. Also I guess to answer the OP's question is that the container's vertical size must be at at least twice the vertical size of the "foregroundView" (for some reason). If I'm correct in this the message is a little confusing. If anything the container view is not tall enough.

**Comment by ryandailey100** [comment]
When will this problem be fixed?? I really want to use folding cell in my project, but nothing works! Please update this, thank.

**Comment by joaoh82** [comment]
I am getting nil from UIGraphicsGetCurrentContext() in pb_takeSnapshot(_ frame: CGRect) -> UIImage?.

Is there a solution for this?!

**Comment by 1159148169** [comment]
I make a demo according to the document and I set the itemCount to 3.You can change the "@IBInspectable open var itemCount: NSInteger" to 3 or 4,then your demo should not crash again.

**Comment by Derek-X-Wang** [comment]
Make a fix direct on the source code may not be a good idea (since I download through cocoapods).

However, the doc is incomplete and I have no idea why they assert on itemCount.

The best way to avoid this crash(as it shows in demo) is to define itemCount>2 in Folding Cell's User Defined Runtime Attributes.

<img width="206" alt="screen shot 2017-03-18 at 5 11 35 am" src="https://cloud.githubusercontent.com/assets/6364170/24071872/94757430-0b99-11e7-99a5-07d80fe24e9f.png">
<img width="258" alt="screen shot 2017-03-18 at 5 12 01 am" src="https://cloud.githubusercontent.com/assets/6364170/24071873/98c5ba40-0b99-11e7-881f-eb25a48c6e06.png">

**Comment by Arcrammer** [comment]
Hmm this error is still happening for me no matter the `itemCount`.

**Comment by KumaresanSubramaniam** [comment]
Just replace assert method in  FoldingCell class
directly set assert value like,
assert(true, "contanerView.height too high")

**Comment by imnontachai** [comment]
Same problem to me. Because I am misunderstood for this component.

I made a constraint top (for container view) reference to foreground view which is my mistake. So, my solution was I changed reference of constraint top to parent view instead.

Sorry for my English, but I wanna help somebody that have the same problem with me.

**Comment by ober01** [comment]
#55
