### ISSUE TITLE
assertion failed: contanerView.height too high

### ISSUE THREAD

**Issue by lxinghe** [Ramotion/folding-cell#80]
So how should I solve this problem?

**Comment by pableiros** [comment]
How did you solve it?

**Comment by imnontachai** [comment]
Same problem to me. Because I am misunderstood for this component.

I made a constraint top (for container view) reference to foreground view which is my mistake. So, my solution was I changed reference of constraint top to parent view instead.

Sorry for my English, but I wanna help somebody that have the same problem with me.

**Comment by lucascarletti** [comment]
Not sure if I really understood it, however what seems to happen is that when cell is trying to unfold itself, the number of times animation will unfold(itemCount), needs to be relative to the height of cell. I solved the assert error by setting 6 at itemCount for a cell who's open height is 202 in storyboard IBInspectable property for my foldingCell. Error was given as cell is trying to animate the unfold or fold and it's height is too big to few unfold animations(eg: height is too big and it tries to unfold with the default 2 opening unfold animations, which crashes as it needs more animations for unfold it properly).

However, still have no success adding folding cell to my project. Now when cell unfolds, can't find where container view is. Still spending lots of hours trying to implement it, but hopefully it will work out just fine! :)
