### ISSUE TITLE
Returning null from UIGraphicsGetCurrentContext, why?

### ISSUE THREAD

**Issue by cpvbruno** [Ramotion/folding-cell#89]
<img width="1127" alt="screen shot 2017-01-11 at 01 07 48" src="https://cloud.githubusercontent.com/assets/5808343/21833817/740eb2c0-d79a-11e6-9cf3-3d0e41ff8e86.png">

**Comment by kirbec** [comment]
I am getting the same problem, please help

**Comment by kirbec** [comment]
the reason why mine wasn't working was because of doing the constraints wrong. Look at the video in the documentation if you're getting the same problem

**Comment by cpvbruno** [comment]
@kirbec yeah.. I stopped trying and restart configuring my project based on sample and now it worked. It was probably because of the constraints configuration, thanks.

**Comment by Vixaer** [comment]
Currently facing this issue.
It'll be great if anyone could describe what did you do when fixed it

**Comment by odyth** [comment]
I don't use this framework, but google sent me here because I to was getting a crash with UIGraphicsGetCurrentContext being nil, want to help future googlers. @xwcao put me on the right track, your width and height both have to be greater than 0 when calling UIGraphicsBeginImageContextWithOptions otherwise you'll get nil.
